name: Build firmware for A5-V11


on:
  # Allow running this workflow manually
  workflow_dispatch:
  workflow_call:
  push:
    tags:
    - 'v*'

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  ARTIFACTS_TEMP_DIR: /tmp/firmware

jobs:
  set-vars:
    runs-on: ${{ vars.RUNNER }}
    steps:
#    - uses: ./.github/actions/set-vars
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: default version
      id: default_version
      run: |
        V=$(fgrep -w ${GITHUB_REF_NAME} .versions | awk '{ print $2 }' ; exit 0)
        echo "DEFAULT VERSION FOR BRANCH: $V"
        [ -z "$V" ] && V=$(fgrep -w default .versions | awk '{ print $2 }'; exit 0)
        echo "DEFAULT BRANCH DEFINED: $V"
        echo "DEFAULT_VERSION=$V">>$GITHUB_OUTPUT

      shell: bash

    - name: set values
      id: vars
      shell: bash
      run: |
        DEFAULT_VERSION=${{ steps.default_version.outputs.DEFAULT_VERSION }}
        echo github.ref: ${{ github.ref }}
        ref='refs/tags/v'
        if [[ ${{ github.ref }} == *${ref}* ]]; then
          V=$(echo ${{ github.ref }} | cut -d'/' -f3)
          echo "Version from tag is ${v}"
        else
          echo "There is no github tag reference, using default version."
          V=$DEFAULT_VERSION
        fi
        echo "Using version $V for ${{ github.ref }}"
        echo "V=$V" >> $GITHUB_OUTPUT

  build:
    runs-on: ${{ vars.RUNNER }}
    needs: [set-vars]
    env:
      V: "${{ needs.set-vars.outputs.V }}"
      IMAGE_NAME: "${{ needs.set-vars.outputs.IMAGE_NAME }}"
      ARTIFACT_NAME: "${{ needs.set-vars.outputs.ARTIFACT_NAME }}"
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: ./.github/actions/build
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Attach artifacts to release
    needs: [set-vars, build]
    permissions:
      contents: write
    env:
      ARTIFACT_NAME: "${{ needs.set-vars.outputs.ARTIFACT_NAME }}"
      V: "${{ needs.set-vars.outputs.V }}"
    runs-on: ${{ vars.RUNNER }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:

      - name: Test
        id: release-exists
        uses: insightsengineering/release-existence-action@main
        with:
          release-tag: ${{ env.V }}

      - name: Existence result
        run: echo Release existence result "$RE"
        shell: bash
        env:
          RE: ${{ steps.release-exists.outputs.release-exists }}

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          draft: false
#          prerelease: false

#      - run: echo "URL = ${{ steps.create_release.outputs.upload_url }}"

###### FAKE ZIP ######
#      - name: Build project # This would actually build your project, using zip for an example artifact
#        run: |
#          echo "hello" >README.md
#          zip --junk-paths my-artifact README.md

#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
#          asset_path: ./my-artifact.zip
#          asset_name: my-artifact.zip
#          asset_content_type: application/zip
###### FAKE ZIP ######

      - uses: actions/download-artifact@master
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACTS_TEMP_DIR }}/
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          body: ""
          fail_on_unmatched_files: false
          generate_release_notes: false
          append_body: false
          make_latest: true
          files: ${{ env.ARTIFACTS_TEMP_DIR }}/*
