# Check OpenWRT repository for new releases and then create new tag if found
name: Check OpenWRT for new releases

on:
  schedule:
    - cron:  '35 4 * * 1' # Each Monday at 4:35

  # Allow running this workflow manually
  workflow_dispatch:

jobs:
  get-openwrt-version:
    runs-on: ${{ vars.RUNNER }}
    outputs:
      is_in_readme: ${{ steps.is_tag_in_readme.outputs.is_in_readme }}
      version: ${{steps.test.outputs.latest_openwrt_tag}}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch release version
        id: test
        run: echo "latest_openwrt_tag=$(curl -sL https://api.github.com/repos/openwrt/openwrt/releases/latest | jq -r .tag_name)" >> $GITHUB_OUTPUT
      - run: echo "Latest OpenWRT version (latest_openwrt_tag) is ${{steps.test.outputs.latest_openwrt_tag}}"
      - name: Do we have this version in README?
        id: is_tag_in_readme
        run: echo "is_in_readme=$(fgrep -wco '${{steps.test.outputs.latest_openwrt_tag}}' README.md)" >>$GITHUB_OUTPUT
      - run: echo "Is version ${{steps.test.outputs.latest_openwrt_tag}} already in readme? Result ${{steps.is_tag_in_readme.outputs.is_in_readme}}"

  update-readme:
    name: Update README.md
    needs: [get-openwrt-version]
    permissions:
      contents: write
    if: needs.get-openwrt-version.outputs.is_in_readme == '0'
    uses: ./.github/workflows/update_readme.yml
    secrets: inherit


  push-git-tag:
    runs-on: ${{ vars.RUNNER }}
    needs: [get-openwrt-version, update-readme]
    permissions:
      contents: write
    if: needs.get-openwrt-version.outputs.is_in_readme == '0'
    steps:
      - name: Push new tag
        uses: ./.github/actions/push-git-tag
        env:
          version: ${{ needs.get-openwrt-version.outputs.version }}
        with:
          tag: ${{ env.version }}

  trigger-build:
    runs-on: ${{ vars.RUNNER }}
    needs: [push-git-tag]
    if: needs.get-openwrt-version.outputs.is_in_readme == '0'
    steps:
      - run: gh workflow run "Build firmware for A5-V11" -r v23.05.4
        env:
          GH_TOKEN: "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"


#  push-git-tag:
#    runs-on: ${{ vars.RUNNER }}
#    needs: [get-openwrt-version, update-readme]
#    env:
#      version: ${{ needs.get-openwrt-version.outputs.version }}
#    permissions:
#      contents: write
#    if: needs.get-openwrt-version.outputs.is_in_readme == '0'
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          ref: ${{ github.head_ref }}
#      - run: |
#          git config --local user.name "github-actions[bot]"
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git tag ${{ env.version }}
#          git push origin ${{ env.version }}

#  build-release:
#    needs: [push-git-tag]
#    permissions:
#      contents: write
#      attestations: write
#      packages: write
#      id-token: write
#    if: needs.get-openwrt-version.outputs.is_in_readme == '0'
#    uses: ./.github/workflows/build.yml
#    secrets: inherit

