name: Common workflow

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  common:
    name: Common
    runs-on: ${{ inputs.runner }}
    steps:
      - run: echo "Hello World"
